config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'about', to: 'about#index'

  # course routing
  get 'courses', to: 'course#index'
  get '/courses/:slug', to: 'course#show', as: 'course'

  # order and payment
  get '/checkout/:id/order', to: 'orders#show', as: 'checkout'
  post '/payment/:id/order', to: 'orders#create', as: 'order'
  post '/webhook/notification', to: 'orders#notification', as: 'notification'

  devise_for :users, controllers: { passwords: 'passwords' }
  
  namespace :admins do
    resources :dashboard
    resources :categories
    resources :speakers
    resources :courses
    resources :videos
    resources :users
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: { message: "Category name can't be blank." }, uniqueness: 
  { message: ->(object, data) do
      "Category #{data[:value]} is already taken."
    end 
  }
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < AdminsController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if current_user
      @category.created_by = set_current_user
      @category.updated_by = set_current_user
    end
    respond_to do |format|
      if @category.save
        format.html { redirect_to admins_categories_path, notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if current_user
      @category.updated_by = set_current_user
    end

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admins_categories_path, notice: "Category was successfully updated." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    redirect_to admins_categories_path, notice: "Category was successfully deleted."
  end

  protected

    def set_current_user
      user = User.full_name(current_user)
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def is_admin?
      if current_user.role != 'admin'
        redirect_to root_path
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admins/categories/_form.html.erb
<%= form_with model: category, url: url do |f| %>
  <div class="mb-3 form-group">
    <%= f.label :name do %>Category name <span class="text-danger">*</span><% end %>
    <%= f.text_field :name, placeholder: "Input category name", autofocus: true,  class: "form-control" %>
    <span class="text-danger"><%= category.errors[:name].first %></span>
  </div>

  <div class="mb-3 form-group">
    <%= button_tag :submit, class: "edu-btn btn-medium"%>
  </div>
<% end %>

app/views/admins/categories/edit.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">
      <div class="col-lg-12 ">
        <h1 class="text-dark">Edit category</h1>
        <%= link_to admins_categories_path, class: "edu-btn btn-medium" do %>Back<% end %>
        <div class="login-form-box shadow-sm">
          <%= render "form", category: @category, url: admins_category_path  %>
        </div>
      </div>
    </div>  
  </div>
</section>

app/views/admins/categories/index.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">

      <% if notice %>
      <div class="col-lg-12">
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      </div> 
      <% end %>
      
      <div class="col-lg-12">
        <h1 class="text-dark">Categories</h1>
        <div class="login-form-box shadow-sm">
          <h4 class="card-title text-dark"><%= link_to new_admins_category_path, class: "edu-btn btn-medium mt-3 mb-3" do %>Create New Category
            <i class="icon-4"></i>
            <% end %>
          </h4>
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th scope="col">Category name</th>
                <th scope="col">Created by</th>
                <th scope="col">Updated by</th>
                <th scope="col">Created at</th>
                <th scope="col">Updated at</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
            <% @categories.each do |category| %>
              <tr>
                <th><%= category.name %></th>
                <th><%= category.created_by %></th>
                <th><%= category.updated_by %></th>
                <th><%= category.created_at %></th>
                <th><%= category.updated_at %></th>
                <th><%= link_to "Edit", edit_admins_category_path(category), class: "btn btn-outline-warning btn-lg mb-2" %> <%= button_to "Delete", admins_category_path(category), method: :delete, class: "btn btn-outline-danger btn-lg", form: { data: { turbo_confirm: "Are you sure?" } } %></th>
              </tr>
            <% end %>
            </tbody>
          </table>
          <nav aria-label="Page navigation example">
            <ul class="pagination pagination-lg">
              <li class="page-item"><a class="page-link" href="#">Previous</a></li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
          </nav>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/admins/categories/new.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">
      <div class="col-lg-12 ">
        <h1 class="text-dark">Add new category</h1>
        <%= link_to admins_categories_path, class: "edu-btn btn-medium" do %>Back<% end %>
        <div class="login-form-box shadow-sm">
          <%= render "form", category: @category, url: admins_categories_path  %>
        </div>
      </div>
    </div>  
  </div>
</section>