config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'about', to: 'about#index'

  # course routing
  get 'courses', to: 'course#index'
  get '/courses/:slug', to: 'course#show', as: 'course'

  # order and payment
  get '/checkout/:id/order', to: 'orders#show', as: 'checkout'
  post '/payment/:id/order', to: 'orders#create', as: 'order'
  post '/webhook/notification', to: 'orders#notification', as: 'notification'

  devise_for :users, controllers: { passwords: 'passwords' }
  
  namespace :admins do
    resources :dashboard
    resources :categories
    resources :speakers
    resources :courses
    resources :videos
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord

  enum :role, [:member, :admin]

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  validates_presence_of :first_name, presence: true, :message => "First name can't be blank"
  validates_presence_of :last_name, presence: true, :message => "Last name can't be blank"
  validates_presence_of :phone_number, presence: true, :message => "Phone number can't be blank."

  def self.full_name(current_user)
    current_user.first_name + " " + current_user.last_name
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminsController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admins_users_path, notice: "User was successfully updated." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_path, notice: "User was successfully deleted."
  end

  protected

  def set_current_user
    user = User.full_name(current_user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :role)
  end

  def is_admin?
    if current_user.role != 'admin'
      redirect_to root_path
    end
  end

end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/views/admins/users/_form.html.erb
<%= link_to admins_users_path, class: "edu-btn btn-medium mt-3" do %>Back to users <i class="icon-4"></i><% end %>

<%= form_with model: user, url: url, class: "mt-5" do |f| %>

    <div class="mb-3 form-group">
      <%= f.label :first_name do %>First Name <span class="text-danger">*</span><% end %>
      <%= f.text_field :first_name, placeholder: "Input first name", autofocus: true,  class: "form-control" %>
    </div>

    <div class="mb-3 form-group">
      <%= f.label :role do %>Role <span class="text-danger">*</span><% end %>
      <%= f.select :role, [["Admin", "admin"], ["Member", "member"]], class: "form-control" %>
    </div>

    <div class="mb-3 form-group">
      <%= button_tag :submit, class: "edu-btn btn-medium"%>
    </div>
<% end %>

app/views/admins/users/edit.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">
      <div class="col-lg-12 ">
        <h1 class="text-dark">Edit User</h1>
        
        <div class="login-form-box shadow">
          <div class="card">
            <div class="card-body p-5">
              <%= render "form", user: @user, url: admins_user_path %>
            </div>
        </div>
        </div>
      </div>
    </div>  
  </div>
</section>

app/views/admins/users/index.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">

      <% if notice %>
      <div class="col-lg-12">
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      </div> 
      <% end %>
      
      <div class="col-lg-12">
        <h1 class="text-dark">Users</h1>
        <div class="login-form-box shadow">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title text-dark"><%= link_to new_admins_user_path, class: "edu-btn btn-medium mt-3 mb-3" do %>Create new speaker
                <i class="icon-4"></i>
                <% end %>
              </h4>
              <table class="table table-hover table-striped table-bordered">
                <thead>
                  <tr>
                    <th scope="col">Email</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Role</th>
                    <th scope="col">Created at</th>
                    <th scope="col">Updated at</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <th><%= user.email %></th>
                    <th><%= user.first_name %></th>
                    <th><%= user.last_name %></th>
                    <th><%= user.phone_number %></th>
                    <th><%= user.role %></th>
                    <th><%= user.created_at %></th>
                    <th><%= user.updated_at %></th>
                    <th><%= link_to "Edit", edit_admins_user_path(user), class: "btn btn-outline-warning btn-lg mb-2" %> <%= button_to "Delete", admins_user_path(user), method: :delete, class: "btn btn-outline-danger btn-lg", form: { data: { turbo_confirm: "Are you sure?" } } %></th>
                  </tr>
                <% end %>
                </tbody>
              </table>
              <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg">
                  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
              </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</section>

app/views/admins/users/new.html.erb
<section class="account-page-area">
  <div class="container position-relative">
    <div class="row g-5 justify-content-center mt-3 mb-5">
      <div class="col-lg-12 ">
        <h1 class="text-dark">Add new speaker</h1>
        
        <div class="login-form-box shadow">
          <div class="card">
            <div class="card-body p-5">
              <%= render "form", speaker: @speaker, url: admins_speakers_path %>
            </div>
        </div>
        </div>
      </div>
    </div>  
  </div>
</section>