config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'about', to: 'about#index'

  # course routing
  get 'courses', to: 'course#index'
  get '/courses/:slug', to: 'course#show', as: 'course'

  # order and payment
  get '/checkout/:id/order', to: 'orders#show', as: 'checkout'
  post '/payment/:id/order', to: 'orders#create', as: 'order'
  post '/webhook/notification', to: 'orders#notification', as: 'notification'

  devise_for :users, controllers: { passwords: 'passwords' }
  
  namespace :admins do
    resources :dashboard
    resources :categories
    resources :speakers
    resources :courses
    resources :videos
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: { message: "Category name can't be blank." }, uniqueness: 
  { message: ->(object, data) do
      "Category #{data[:value]} is already taken."
    end 
  }
end

app/models/course.rb
class Course < ApplicationRecord
  # validation
  validates :title, presence: { message: "Title can't be blank." }, uniqueness: 
  { message: ->(object, data) do
    "Title #{data[:value]} is already taken."
  end 
  }

# query
scope :by_status_and_type, -> (sort) { where(status: 'published', sort: sort) }
scope :by_category, -> (category_id) { where(category_id: category_id) }
scope :by_speaker, -> (speaker_id) { where(speaker_id: speaker_id) }

# enum
enum :status, [:draft, :published]
enum :sort, [:playback, :live]

# relationship
belongs_to :category, foreign_key: "category_id"
belongs_to :speaker, foreign_key: "speaker_id"
has_one_attached :image
has_rich_text :body

# trigger
after_validation :set_slug, only: [:create, :update]
  
def format_number(number)
  num_groups = number.to_s.chars.to_a.reverse.each_slice(3)
  num_groups.map(&:join).join(',').reverse
end

private
  def set_slug
    self.slug = title.to_s.parameterize
  end
end

app/models/my_course.rb
class MyCourse < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  belongs_to :course, foreign_key: "course_id"
end

app/models/payment_log.rb
class PaymentLog < ApplicationRecord
end

app/models/speaker.rb
class Speaker < ApplicationRecord

  has_rich_text :body 
  
  validates :full_name, presence: { message: "Spekaer name can't be blank." }, uniqueness: 
  { message: ->(object, data) do
      "Speaker with name #{data[:value]} is already taken."
    end 
  }
  validates :title, presence: { message: "Title can't be blank." }
  validates :body, presence: { message: "Description can't be blank." }
end

app/models/user.rb
class User < ApplicationRecord

  enum :role, [:member, :admin]

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  validates_presence_of :first_name, presence: true, :message => "First name can't be blank"
  validates_presence_of :last_name, presence: true, :message => "Last name can't be blank"
  validates_presence_of :phone_number, presence: true, :message => "Phone number can't be blank."

  def self.full_name(current_user)
    current_user.first_name + " " + current_user.last_name
  end

end

app/models/video.rb
class Video < ApplicationRecord

  # validation
  validates :subject, presence: { message: "Video title can't be blank." }
  validates :course_id, presence: { message: "Course title can't be blank." }
  validates :url_video, presence: { message: "URL video title can't be blank." }, uniqueness: 
  { message: ->(object, data) do
    "URL video #{data[:value]} is already taken."
  end 
  }

  belongs_to :course, foreign_key: "course_id"
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout "admins"
  
  def index
  end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def index
    @courses = Course.includes(:category)
    
    category = Category.select(:id).where(name: params[:category]).take
    
    speaker = Speaker.select(:id).where(full_name: params[:speaker]).take

    @courses = @courses.where(sort: params[:type]) unless params[:type].nil?
    # jika parameter kategori jika tidak kosong tampilkan berdasarakan kategori
    @courses = @courses.by_category(category) unless category.nil?
    # jika parameter speaker jika tidak kosong tampilkan berdasarkan speaker
    @courses = @courses.by_speaker(speaker) unless speaker.nil?
     # jika parameter kosong maka tampilkan semua course order by created_at descending
    @courses = @courses.order(created_at: :desc).page(params[:page]).per(10)
    # total kursus
    @total_course = @courses.count
  end

  def show
    @course = Course.includes(:speaker, :category).where(slug: params[:slug]).take
    if @course.nil? || current_user.nil?
      flash[:alert] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path 
    end
    my_course = MyCourse.where(course_id: @course.id, user_id: current_user.id).take
    redirect_to root_path unless my_course
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.includes(:category, :speaker).where(status: 'published')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/admins/_navbar.html.erb
<header class="edu-header header-style-1 header-fullwidth">
	<div class="header-mainmenu">
			<div class="container-fluid">
					<div class="header-navbar">
							<div class="header-brand">
									<div class="logo">
											<%= link_to admins_dashboard_index_path do %>
													<%= image_tag ("logo/haraacademy_white.png"), alt: "Hara Academy", class: "logo-light" %>
											<% end %>
									</div>
							</div>
							<div class="header-mainnav">
									<nav class="mainmenu-nav">
											<ul class="mainmenu">
													<li><%= link_to "Dashboard", admins_dashboard_index_path %></li>
													<li><%= link_to "Categories", admins_categories_path %></li>
													<li><%= link_to "Speakers", admins_speakers_path %></li>
													<li><%= link_to "Courses", admins_courses_path %></li>
													<li><%= link_to "Course of member", admins_courses_path %></li>
													<li><%= link_to "Users", admins_users_path %></li>
											</ul>
									</nav>
							</div>
							<div class="header-right">
									<ul class="header-action">
											<li class="mobile-menu-bar d-block d-xl-none">
													<button class="hamberger-button" data-controller="menu" data-action="click->menu#hamburger">
															<i class="icon-54"></i>
													</button>
											</li>
									</ul>
							</div>
					</div>
			</div>
	</div>
	<div class="popup-mobile-menu" id="popUpMobile">
			<div class="inner">
					<div class="header-top">
							<div class="logo">
									<%= link_to admins_dashboard_index_path do %>
											<%= image_tag ("logo/haraacademy_white.png"), alt: "Hara Academy", class: "logo-light" %>
									<% end %>
							</div>
							<div class="close-menu" data-controller="menu" data-action="click->menu#close">
									<button class="close-button">
											<i class="icon-73"></i>
									</button>
							</div>
					</div>
					<ul class="mainmenu">
						<li><%= link_to "Dashboard", admins_dashboard_index_path %></li>
						<li><%= link_to "Categories", admins_categories_path %></li>
						<li><%= link_to "Speakers", admins_speakers_path %></li>
						<li><%= link_to "Courses", admins_courses_path %></li>
						<li><%= link_to "Course of member", admins_courses_path %></li>
						<li><%= link_to "Users", admins_users_path %></li>
					</ul>
			</div>
	</div>
	
</header>